### ISSUE TITLE
Blackstone golem arm causing crashes

### ISSUE THREAD

**Issue by Peganox** [Globox1997/AdventureZ#37] opened 2021-06-01 05:46 UTC
I've tried using the arm a few times as well as spawning in the golem and having it shoot me and every time the rock-throwing rendering causes me to crash 
Ive attached the crash report here
[crash-2021-06-01_01.36.49-client.txt](https://github.com/Globox1997/AdventureZ/files/6573656/crash-2021-06-01_01.36.49-client.txt)

**Comment by Globox1997** [comment] 2021-06-01 07:36
Thanks for the report, I'll fix it

**Comment by Globox1997** [comment] 2021-06-01 08:12
Fixed with [https://github.com/Globox1997/AdventureZ/commit/c2624d5d0c8cff66bbec42604f1c8a5deabe0aad](https://github.com/Globox1997/AdventureZ/commit/c2624d5d0c8cff66bbec42604f1c8a5deabe0aad)

**Comment by HyperlyBola** [comment] 2021-06-03 11:10
I just got the crash too even after the fix. And now I can't start the server properly without it crashing on its own
[crash-2021-06-03_06.08.33-server.txt](https://github.com/Globox1997/AdventureZ/files/6591212/crash-2021-06-03_06.08.33-server.txt)

**Comment by Globox1997** [comment] 2021-06-03 11:42
This is a different crash ;) when does this exactly happen?

**Comment by HyperlyBola** [comment] 2021-06-03 11:56
It only happens when I get hit by the rock from the golem, when it just shoots and misses it doesn't really happen or log any errors. at least not that i know of.

**Comment by Globox1997** [comment] 2021-06-03 13:56
mh I can't seem to reproduce this crash ... may be a incompatibility?

**Comment by Globox1997** [comment] 2021-06-03 20:56
This doesn't happen when adventurez only is installed?

**Comment by HyperlyBola** [comment] 2021-06-03 21:08
I will test it out with just AdventureZ, but I have a feeling its being caused by one of the performance or rendering related mods I have. I was using Canvas shaders during the time so that might also be it. But also not because the server would crash on its own.

**Comment by HyperlyBola** [comment] 2021-06-03 22:20
[crash-2021-06-03_17.19.23-server.txt](https://github.com/Globox1997/AdventureZ/files/6594635/crash-2021-06-03_17.19.23-server.txt)

It is not an incompatibility thank god 👍 i'm not gonna bother finding what mod is causing it if it was

**Comment by Globox1997** [comment] 2021-06-04 07:34
[test.zip](https://github.com/Globox1997/AdventureZ/files/6596558/test.zip)
please test both versions (first 1.2.4) if it still breaks. you have to unzip the files

**Comment by HyperlyBola** [comment] 2021-06-04 08:29
Oh nice, 1.2.5 fixed it. I didn't get any errors in client or server logs on 1.2.5, but I still got the normal crash from 1.2.4. Here it is again if you want the new one. That was like hyper fast bug fixing btw


[crash1.2.4.txt](https://github.com/Globox1997/AdventureZ/files/6596920/crash1.2.4.txt)

**Comment by Globox1997** [comment] 2021-06-04 08:38
alright nice ;)

**Closed by Globox1997** 2021-06-04 08:38 UTC
